# Generated by Django 5.0.4 on 2024-05-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anilistuser',
            old_name='name',
            new_name='username',
        ),
    ]
