# Generated by Django 5.0.4 on 2024-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anilistuser',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Profile picture'),
        ),
    ]
