# Generated by Django 5.0.4 on 2024-05-17 14:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_anilistuser_profile_pic_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='UA', max_length=2),
        ),
    ]
